name: uts_app_healthmate_islami
description: "HealthMate Islami â€“ Aplikasi Pencatat Kesehatan Harian (UTS & UAS Upgrade)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^5.0.0

  # HTTP & API
  http: ^1.2.2

  # FIREBASE (core + auth + firestore)
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.2.1

  # OPTIONAL tapi disarankan (loading animation)
  flutter_spinkit: ^5.2.0
  
  # ðŸ“Š CHART
  fl_chart: ^0.68.0

  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/activity_data.json
    - assets/logo.png
    - assets/profile.jpg
